import {
  SipaDiacritic,
  SipaConsonant,
  SipaVowel,
  SipaSpeciesTranscription,
} from '../types';

// ============================================================================
// 1. VOCAL TRACT MECHANICS & DIACRITICS
// ============================================================================
export const SIPA_DIACRITICS: SipaDiacritic[] = [
  {
    id: 'diacritic-air-sac',
    symbol: '\u0303', // ◌̃ Combining Tilde
    displaySymbol: '◌̃',
    name: 'Air-Sac Resonance',
    phoneticModifier: 'Subhyoid Ingress/Egress Chambering',
    acousticMechanism: 'Acoustic coupling with large subhyoid or laryngeal air sacs, creating low resonant peaks (sub-200 Hz formants) and anti-resonances.',
    example: '[ ʊ̃ ]',
    exampleTranscription: 'Siamang throat-sac resonant boom call & Orangutan long-call reverberation',
    vocalTractMechanism: 'Subhyoid air-sac inflation expands resonant acoustic chamber volume by 180–400%, lowering fundamental resonance without lengthening oral cavity.',
    frequencyRangeHz: [80, 220],
    usdPropertyBinding: 'primvars:acoustic:subhyoidAirSacVolumeM3 = 0.0035; primvars:acoustic:resonanceQ = 8.4',
  },
  {
    id: 'diacritic-lip-smack',
    symbol: '\u034B', // ◌͋ Combining Homorganic Nasal / Ingressive Smack
    displaySymbol: '◌͋',
    name: 'Lip-Smack / Ingress',
    phoneticModifier: 'Inward Airflow with Labial Puckering',
    acousticMechanism: 'Non-vocalized acoustic transient generated by negative intra-oral pressure and sudden wet labial detachment.',
    example: '[ p͋ ]',
    exampleTranscription: 'Gelada contact click-whistle & Macaque affiliative reassurance rhythm',
    vocalTractMechanism: 'Everted mucosal lips create airtight seal; rapid mandible depression pulls air inward immediately prior to lip separation.',
    frequencyRangeHz: [2400, 5800],
    usdPropertyBinding: 'blendshapes:lipPucker = 0.92; blendshapes:jawDepressVelocity = 3.2',
  },
  {
    id: 'diacritic-subharmonic',
    symbol: '\u0349', // ◌͉ Combining Left Angle Below / Sub-harmonic pulse
    displaySymbol: '◌͉',
    name: 'Sub-Harmonic Tremor',
    phoneticModifier: 'Low-Frequency Diaphragm / Chest Pulse',
    acousticMechanism: 'Sub-harmonic bifurcation (f0/2, f0/3) driven by heavy vocal fold vibration coupled with rapid thoracic cage pulses.',
    example: '[ ɓ͉ ]',
    exampleTranscription: 'Gorilla chest-beat-grunt & Baboon dominance roar under-rumble',
    vocalTractMechanism: 'Thoracic diaphragm spasms induce amplitude modulation at 12–24 Hz over continuous laryngeal phonation.',
    frequencyRangeHz: [45, 140],
    usdPropertyBinding: 'primvars:acoustic:subharmonicTremorModulation = 18.0; primvars:acoustic:thoracicPulseForce = 42.0',
  },
  {
    id: 'diacritic-coarticulation',
    symbol: '\u0361', // ◌͡ Combining Double Inverted Breve
    displaySymbol: '◌͡',
    name: 'Rapid Co-articulation',
    phoneticModifier: 'Dual Phonation in Single Breath Pulse',
    acousticMechanism: 'Simultaneous or seamless micro-staccato transitions between explosive stop and fricative or vowel without glottal reset.',
    example: '[ k͡x ]',
    exampleTranscription: 'Pan troglodytes pant-bark & Vervet predatory leopard warning',
    vocalTractMechanism: 'Posterior tongue dorsum impacts soft palate concurrently with laryngeal constriction, discharging single pressurized air packet.',
    frequencyRangeHz: [600, 2200],
    usdPropertyBinding: 'primvars:acoustic:coarticulationDelayMs = 0.0; blendshapes:tonguePalatalSeal = 1.0',
  },
  {
    id: 'diacritic-inhaled',
    symbol: '↑',
    displaySymbol: '↑',
    name: 'Inhaled Ingressive Phonation',
    phoneticModifier: 'Ingressive Airflow across Glottis',
    acousticMechanism: 'Phonation produced while drawing air rapidly inward into lungs; characteristic strained, high-friction acoustic texture.',
    example: '[ ɑ↑ ]',
    exampleTranscription: 'Pan troglodytes pant-hoot phase 2 inhaled recovery pant',
    vocalTractMechanism: 'Negative subglottal pressure draws vocal folds into inverted vibration mode, generating asymmetric saw wave.',
    frequencyRangeHz: [420, 1100],
    usdPropertyBinding: 'primvars:acoustic:airflowDirection = "ingress"; primvars:acoustic:subglottalPressure = -1400.0',
  },
  {
    id: 'diacritic-exhaled',
    symbol: '↓',
    displaySymbol: '↓',
    name: 'Exhaled Egressive Phonation',
    phoneticModifier: 'Egressive Airflow across Glottis',
    acousticMechanism: 'Standard outward pulmonic pressure wave driving mucosal wave oscillation across vocal folds.',
    example: '[ ɑ↓ ]',
    exampleTranscription: 'Macaque travel grunt & Chimpanzee let-down phase exhaust',
    vocalTractMechanism: 'Abdominal muscular contraction forces positive subglottal pressure outward through vocal tract.',
    frequencyRangeHz: [350, 950],
    usdPropertyBinding: 'primvars:acoustic:airflowDirection = "egress"; primvars:acoustic:subglottalPressure = 2200.0',
  },
];

// ============================================================================
// 2. ACOUSTIC CONSONANTS (Percussive & Non-Pulmonic)
// ============================================================================
export const SIPA_CONSONANTS: SipaConsonant[] = [
  {
    id: 'consonant-labial-lipsmack',
    symbol: 'ǂ',
    name: 'Labial Lip-Smack',
    mechanism: 'Non-vocal sound produced by smacking wet mucosal lips repeatedly in rapid succession (3–7 Hz rhythm).',
    functionalRole: 'Affiliative social re-engagement, appeasement, grooming prelude, and reconciliation.',
    speciesUsage: ['Rhesus Macaque (Macaca mulatta)', 'Olive Baboon (Papio anubis)', 'Gelada (Theropithecus gelada)'],
    acousticProfile: 'Broadband percussive clicks centered at 3,200–5,500 Hz with fast attack (<4ms) and zero harmonic tail.',
    defaultFrequencyHz: 4200,
    percussiveType: 'labial',
    pulmonic: false,
    usdToken: 'usd:semiotics:sipa:labial_click_smack',
  },
  {
    id: 'consonant-tooth-clack',
    symbol: 'ʘ̂',
    name: 'Tooth-Clack Transient',
    mechanism: 'Rapid vertical jaw-clacking and incisor contact without vocal cord engagement.',
    functionalRole: 'Extreme anxiety display, acute fear submission, or nervous appeasement toward dominant conspecifics.',
    speciesUsage: ['Rhesus Macaque (Macaca mulatta)', 'Crab-eating Macaque (Macaca fascicularis)', 'Sooty Mangabey'],
    acousticProfile: 'Sharp, dry enamel impact transients with fast decaying resonant ring between 4,800–7,200 Hz.',
    defaultFrequencyHz: 5800,
    percussiveType: 'dental',
    pulmonic: false,
    usdToken: 'usd:semiotics:sipa:tooth_clack_transient',
  },
  {
    id: 'consonant-laryngeal-hiss',
    symbol: 'ɓ̥',
    name: 'Laryngeal Hiss / Play-Pant',
    mechanism: 'Inhaled or exhaled glottal friction with widely parted vocal folds and relaxed open jaw.',
    functionalRole: 'Play initiation, tickle response, affiliative chasing games, social non-threat meta-communicative signal.',
    speciesUsage: ['Chimpanzee (Pan troglodytes)', 'Bonobo (Pan paniscus)', 'Western Gorilla (Gorilla gorilla)'],
    acousticProfile: 'Unvoiced breathy turbulent white noise with formants modulated by oral cavity volume (800–2,400 Hz).',
    defaultFrequencyHz: 1600,
    percussiveType: 'laryngeal',
    pulmonic: true,
    usdToken: 'usd:semiotics:sipa:laryngeal_play_pant',
  },
  {
    id: 'consonant-bark-transient',
    symbol: 'ʞ',
    name: 'Bark-Transient Stop',
    mechanism: 'Explosive, unvoiced glottal stop driven by a sudden, violent muscular burst from the diaphragm.',
    functionalRole: 'Abrupt predator detection trigger, territorial challenge, staccato troop alert.',
    speciesUsage: ['Vervet Monkey (Chlorocebus pygerythrus)', 'Baboon (Papio)', 'Chimpanzee (Pan troglodytes)'],
    acousticProfile: 'Sharp impulse wavefront followed by rapid dampening; spectral centroid 900–1,800 Hz, rise time <8ms.',
    defaultFrequencyHz: 1250,
    percussiveType: 'glottal_burst',
    pulmonic: true,
    usdToken: 'usd:semiotics:sipa:bark_transient_burst',
  },
];

// ============================================================================
// 3. VOWELS & RESONANTS (Pitch & Contour)
// ============================================================================
export const SIPA_VOWELS: SipaVowel[] = [
  {
    id: 'vowel-high-front-i',
    symbol: 'i',
    name: 'High Front Chatter Vowel',
    commonCallName: 'Alarm Chatter / High Distress Pip',
    vowelHeight: 'high',
    vowelBackness: 'front',
    lipPosition: 'open_grimace',
    description: 'High-frequency narrow vocal tract resonance with bared-teeth retraction, common in snake and predator alarm sequences.',
    speciesDistribution: ['Vervet Monkey (Chlorocebus pygerythrus)', 'Capuchin (Cebus)', 'Squirrel Monkey (Saimiri)'],
    baseFrequencyHz: 2200,
    formants: { f1: 320, f2: 2400 },
    usdToken: 'usd:semiotics:sipa:vowel_high_front_i',
  },
  {
    id: 'vowel-high-back-u',
    symbol: 'u',
    name: 'High Back Resonant Vowel',
    commonCallName: 'Canopy Distance Whistle / Pipe',
    vowelHeight: 'high',
    vowelBackness: 'back',
    lipPosition: 'rounded',
    description: 'Narrow rounded lip aperture maximizing acoustic transmission through dense equatorial canopy leaves.',
    speciesDistribution: ['Gibbon (Hylobatidae)', 'Siamang (Symphalangus)', 'Howler Monkey (Alouatta)'],
    baseFrequencyHz: 650,
    formants: { f1: 300, f2: 870 },
    usdToken: 'usd:semiotics:sipa:vowel_high_back_u',
  },
  {
    id: 'vowel-mid-central-schwa',
    symbol: 'ə',
    name: 'Mid Central Neutral Resonant',
    commonCallName: 'Coughing Bark / Low Contact Murmur',
    vowelHeight: 'mid',
    vowelBackness: 'central',
    lipPosition: 'unrounded',
    description: 'Neutral open tract configuration with minimal muscular tension, utilized for energy-efficient troop spacing barks.',
    speciesDistribution: ['Vervet Monkey (Chlorocebus pygerythrus)', 'Chimpanzee (Pan troglodytes)', 'Macaque (Macaca)'],
    baseFrequencyHz: 480,
    formants: { f1: 520, f2: 1520 },
    usdToken: 'usd:semiotics:sipa:vowel_mid_central_schwa',
  },
  {
    id: 'vowel-mid-back-o',
    symbol: 'o',
    name: 'Mid Back Rounded Chamber Vowel',
    commonCallName: 'Mellow Travel Hoo / Rallying Call',
    vowelHeight: 'mid',
    vowelBackness: 'back',
    lipPosition: 'rounded',
    description: 'Protruded lips form a cylindrical horn extension that projects sound along riverbanks and atoll corridors.',
    speciesDistribution: ['Bonobo (Pan paniscus)', 'Orangutan (Pongo)', 'Spider Monkey (Ateles)'],
    baseFrequencyHz: 380,
    formants: { f1: 450, f2: 950 },
    usdToken: 'usd:semiotics:sipa:vowel_mid_back_o',
  },
  {
    id: 'vowel-low-front-ae',
    symbol: 'æ',
    name: 'Low Front Open Threat Vowel',
    commonCallName: 'Leopard Alarm Bark / Agonistic Snarl',
    vowelHeight: 'low',
    vowelBackness: 'front',
    lipPosition: 'open_grimace',
    description: 'Wide jaw drop combined with tongue flattening, producing high sound pressure level (SPL) alert acoustics.',
    speciesDistribution: ['Vervet Monkey (Chlorocebus pygerythrus)', 'Baboon (Papio ursinus)'],
    baseFrequencyHz: 820,
    formants: { f1: 680, f2: 1720 },
    usdToken: 'usd:semiotics:sipa:vowel_low_front_ae',
  },
  {
    id: 'vowel-low-back-alpha',
    symbol: 'ɑ',
    name: 'Low Open Grunt Vowel',
    commonCallName: 'Base Food / Travel / Rest Grunt',
    vowelHeight: 'low',
    vowelBackness: 'back',
    lipPosition: 'unrounded',
    description: 'Base foundational sound in Pan, Pongo, and Macaca. Unconstricted pharyngeal opening providing deep baseline harmonics.',
    speciesDistribution: ['Chimpanzee (Pan troglodytes)', 'Orangutan (Pongo abelii)', 'Rhesus Macaque (Macaca mulatta)'],
    baseFrequencyHz: 280,
    formants: { f1: 760, f2: 1120 },
    usdToken: 'usd:semiotics:sipa:vowel_low_back_alpha',
  },
  {
    id: 'vowel-hoo-call-upsilon',
    symbol: 'ʊ',
    name: 'Rounded Hoo Call Vowel',
    commonCallName: 'Soft Inquiry / Nesting Hoo Call',
    vowelHeight: 'high',
    vowelBackness: 'back',
    lipPosition: 'rounded',
    description: 'Soft, rounded-lip vocalization with near-zero pitch variance. Used for maternal comfort, mild inquiry, or soft approach.',
    speciesDistribution: ['Chimpanzee (Pan troglodytes)', 'Bonobo (Pan paniscus)', 'Siamang (Symphalangus syndactylus)'],
    baseFrequencyHz: 340,
    formants: { f1: 410, f2: 980 },
    usdToken: 'usd:semiotics:sipa:vowel_hoo_call_upsilon',
  },
  {
    id: 'vowel-scream-turned-m',
    symbol: 'ɯ',
    name: 'High Screen / Scream Vowel',
    commonCallName: 'Open-Mouth Extreme Scream / Agonistic Climax',
    vowelHeight: 'high',
    vowelBackness: 'back',
    lipPosition: 'open_grimace',
    description: 'Maximum jaw opening with retracted lip corners, driving high-amplitude chaotic vocal fold oscillation during extreme distress or climax.',
    speciesDistribution: ['Chimpanzee (Pan troglodytes)', 'Rhesus Macaque (Macaca mulatta)', 'Siamang (Symphalangus syndactylus)'],
    baseFrequencyHz: 2600,
    formants: { f1: 850, f2: 2800 },
    usdToken: 'usd:semiotics:sipa:vowel_scream_turned_m',
  },
];

// ============================================================================
// 4. TRANSCRIPTION EXAMPLES ACROSS SPECIES
// ============================================================================
export const SIPA_SPECIES_TRANSCRIPTIONS: SipaSpeciesTranscription[] = [
  {
    id: 'sipa-chimpanzee-pant-hoot',
    species: 'Chimpanzee',
    latinName: 'Pan troglodytes',
    callSequenceName: 'Pant-Hoot Canonical Sequence',
    sIpaRepresentation: '[ ʊ̃↓-ʊ̃↓-ʊ̃↓ ] ──> [ ɓ̥ɑ↑-ɓ̥ɑ↓-ɓ̥ɑ↑-ɓ̥ɑ↓ ] ──> [ ɯː↑-ɯː↑ ] ──> [ ɑ↓-ɑ↓-ə ]',
    behavioralContext: 'Long-distance territory advertising, food arrival celebration, and alpha male social dominance display.',
    ecologicalFunction: 'Acoustic beacon transmitting over 1.5–3 km through tropical rainforest canopy to coordinate party fission-fusion reunions.',
    canopyAcoustics: 'Multi-harmonic structure transitioning from low 220 Hz resonant hoos to deafening 2,800 Hz chaotic screams (>104 dB SPL at 1 meter).',
    phases: [
      {
        phaseNumber: 1,
        name: 'Introduction Phase',
        sipaNotation: '[ ʊ̃↓-ʊ̃↓-ʊ̃↓ ]',
        acousticDescription: 'Soft, slow, rounded-lip hoos with subhyoid air-sac warmth and low pitch variance.',
        respiratoryDynamic: 'egress',
        frequencyHz: 320,
        durationMs: 2400,
        airSacEngagement: true,
      },
      {
        phaseNumber: 2,
        name: 'Build-up Phase',
        sipaNotation: '[ ɓ̥ɑ↑-ɓ̥ɑ↓-ɓ̥ɑ↑-ɓ̥ɑ↓ ]',
        acousticDescription: 'Rapid, breathy, accelerating panting grunts with alternating inhaled/exhaled air movement driven by violent diaphragm pulses.',
        respiratoryDynamic: 'rapid_cycle',
        frequencyHz: 580,
        durationMs: 3200,
        airSacEngagement: false,
      },
      {
        phaseNumber: 3,
        name: 'Climax Phase',
        sipaNotation: '[ ɯː↑-ɯː↑ ]',
        acousticDescription: 'Piercing, chaotic, open-mouth screamed barks with non-linear acoustic phenomena and pitch jumps.',
        respiratoryDynamic: 'ingress',
        frequencyHz: 2450,
        durationMs: 2800,
        airSacEngagement: false,
      },
      {
        phaseNumber: 4,
        name: 'Let-down Phase',
        sipaNotation: '[ ɑ↓-ɑ↓-ə ]',
        acousticDescription: 'Decelerating low-frequency exhaust grunts returning vocal tract to resting tidal respiration.',
        respiratoryDynamic: 'egress',
        frequencyHz: 340,
        durationMs: 1800,
        airSacEngagement: false,
      },
    ],
    usdAudioSchemaAscii: `#usda 1.0
def AudioClip "Chimpanzee_PantHoot_SIPA"
{
    string sipa:canonicalTranscription = "[ ʊ̃↓-ʊ̃↓-ʊ̃↓ ] -> [ ɓ̥ɑ↑-ɓ̥ɑ↓ ] -> [ ɯː↑ ] -> [ ɑ↓ ]"
    float sipa:subhyoidResonanceCutoffHz = 220.0
    float sipa:maxPeakFrequencyHz = 2850.0
    token sipa:respiratoryPumping = "biphasic_ingress_egress"
    float[] sipa:phaseDurationsSec = [ 2.4, 3.2, 2.8, 1.8 ]
}`,
  },
  {
    id: 'sipa-vervet-alarm-calls',
    species: 'Vervet Monkey',
    latinName: 'Chlorocebus pygerythrus',
    callSequenceName: 'Predatory Tri-Modal Alarm Calls',
    sIpaRepresentation: 'Leopard: [ k͡xæ-k͡xæ-k͡xæ ] | Eagle: [ ər-ər-ər-əː ] | Snake: [ ǂ-i-i-i-i ]',
    behavioralContext: 'Referential semantic communication signaling specific predatory threats and evoking distinct escape responses.',
    ecologicalFunction: 'Semantic warning system: leopard alarm triggers immediate tree climbing; eagle alarm triggers scanning sky and hiding in low scrub; snake alarm triggers bipedal posture and scanning grass.',
    canopyAcoustics: 'Staccato abrupt wavebursts engineered to resist environmental wind shearing and reverberation in savannah and gallery forests.',
    phases: [
      {
        phaseNumber: 1,
        name: 'Leopard Alarm Call',
        sipaNotation: '[ k͡xæ-k͡xæ-k͡xæ ]',
        acousticDescription: 'Low, explosive tonal barks with co-articulated velar/glottal onset; high amplitude bursts trigger immediate vertical canopy climb.',
        respiratoryDynamic: 'egress',
        frequencyHz: 820,
        durationMs: 1100,
        airSacEngagement: false,
      },
      {
        phaseNumber: 2,
        name: 'Eagle Alarm Call',
        sipaNotation: '[ ər-ər-ər-əː ]',
        acousticDescription: 'Low-frequency rhythmic coughing grunt with elongated final syllable; troop members instantly look up and dive into dense shrubs.',
        respiratoryDynamic: 'egress',
        frequencyHz: 460,
        durationMs: 1400,
        airSacEngagement: false,
      },
      {
        phaseNumber: 3,
        name: 'Snake Alarm Call',
        sipaNotation: '[ ǂ-i-i-i-i ]',
        acousticDescription: 'High-frequency rapid lip-smack / tooth-chatter followed by sustained dental squeaks; troop members stand bipedally to inspect ground cover.',
        respiratoryDynamic: 'rapid_cycle',
        frequencyHz: 3400,
        durationMs: 1600,
        airSacEngagement: false,
      },
    ],
    usdAudioSchemaAscii: `#usda 1.0
def AudioBehavior "Vervet_SemanticAlarm_SIPA"
{
    dictionary sipa:semanticTriggers = {
        string terrestrial_leopard = "[ k͡xæ-k͡xæ-k͡xæ ]"
        string aerial_eagle = "[ ər-ər-ər-əː ]"
        string ground_snake = "[ ǂ-i-i-i-i ]"
    }
    string sipa:responseProtocol = "context_dependent_escape_vector"
}`,
  },
  {
    id: 'sipa-siamang-great-call',
    species: 'Siamang',
    latinName: 'Symphalangus syndactylus',
    callSequenceName: 'Great Call Duo (Throat-Sac Duet)',
    sIpaRepresentation: 'Male Boom: [ ʊ̃ː↑ ] ──> Bark Chorus: [ k͡xɑ↓-k͡xɑ↓ ] ──> Climax Scream: [ ɯ̃ː↑↑ ]',
    behavioralContext: 'Monogamous pair bond maintenance, territorial boundary defense, and early morning canopy acoustics reinforcement.',
    ecologicalFunction: 'Inflatable subhyoid throat sacs swell to grapefruit size, creating acoustic impedance matching that carries up to 4 km through morning fog.',
    canopyAcoustics: 'Immense low-frequency resonance (120–180 Hz) paired with rapid co-articulated barks and rising female ultrasonic overtones.',
    phases: [
      {
        phaseNumber: 1,
        name: 'Subhyoid Boom Call',
        sipaNotation: '[ ʊ̃ː↑ ]',
        acousticDescription: 'Subhyoid throat-sac inflation produces a deep resonating cavernous boom, acting as a sub-woofer carrier wave across the valley.',
        respiratoryDynamic: 'ingress',
        frequencyHz: 160,
        durationMs: 3100,
        airSacEngagement: true,
      },
      {
        phaseNumber: 2,
        name: 'Duetting Bark Chorus',
        sipaNotation: '[ k͡xɑ↓-k͡xɑ↓ ]',
        acousticDescription: 'Synchronized male-female staccato barks with co-articulated palatal attack projecting directional acoustic localization.',
        respiratoryDynamic: 'egress',
        frequencyHz: 740,
        durationMs: 2600,
        airSacEngagement: true,
      },
      {
        phaseNumber: 3,
        name: 'Female Climax Scream',
        sipaNotation: '[ ɯ̃ː↑↑ ]',
        acousticDescription: 'Accelerating high-pitched throat-sac amplified scream reaching maximum acoustic saturation before synchronized drop.',
        respiratoryDynamic: 'ingress',
        frequencyHz: 1850,
        durationMs: 3400,
        airSacEngagement: true,
      },
    ],
    usdAudioSchemaAscii: `#usda 1.0
def AudioSource "Siamang_ThroatSacDuet_SIPA"
{
    string sipa:duetSignature = "male:[ ʊ̃ː↑ ] + female:[ ɯ̃ː↑↑ ]"
    bool sipa:subhyoidInflationActive = true
    float sipa:subwooferCenterHz = 160.0
    float sipa:climaxDecibelSpl = 112.0
}`,
  },
  {
    id: 'sipa-gelada-contact',
    species: 'Gelada',
    latinName: 'Theropithecus gelada',
    callSequenceName: 'Syncopated Lip-Roll Contact Whistle',
    sIpaRepresentation: '[ p͋ə-p͋ə-p͋ə ] ──> [ ɑ↓-p͋-ɑ↓ ]',
    behavioralContext: 'Grazing band cohesion on high Afroalpine plateaus; complex rhythm mimicking human syllable undulating dynamics.',
    ecologicalFunction: 'Continuous social monitoring while foraging head-down in dense montane grasses without requiring eye contact.',
    canopyAcoustics: 'Rapid undulating pitch contours driven by concurrent lip-flapping and vocal fold phonation (6–9 syllables per second).',
    phases: [
      {
        phaseNumber: 1,
        name: 'Ingressive Lip-Roll',
        sipaNotation: '[ p͋ə-p͋ə-p͋ə ]',
        acousticDescription: 'Rhythmic lip-puckering and inward airflow alternating with neutral central resonance.',
        respiratoryDynamic: 'ingress',
        frequencyHz: 1450,
        durationMs: 1800,
        airSacEngagement: false,
      },
      {
        phaseNumber: 2,
        name: 'Vocalized Glide',
        sipaNotation: '[ ɑ↓-p͋-ɑ↓ ]',
        acousticDescription: 'Low open grunt punctuated by sudden inward labial snap.',
        respiratoryDynamic: 'rapid_cycle',
        frequencyHz: 620,
        durationMs: 1500,
        airSacEngagement: false,
      },
    ],
    usdAudioSchemaAscii: `#usda 1.0
def AudioBehavior "Gelada_LipRoll_SIPA"
{
    string sipa:phonemeChain = "[ p͋ə-p͋ə-p͋ə ]"
    float sipa:syllableRateHz = 7.5
    bool sipa:isIngressiveWhistle = true
}`,
  },
  {
    id: 'sipa-gorilla-chest-beat',
    species: 'Western Lowland Gorilla',
    latinName: 'Gorilla gorilla gorilla',
    callSequenceName: 'Sub-Harmonic Chest-Beat & Grunt Roar',
    sIpaRepresentation: '[ ɓ͉-ɓ͉-ɓ͉ ] ──> [ ɓ͉ɑ↓ ]',
    behavioralContext: 'Silverback dominance assertion, troop protection warning, and spacing signal between neighboring groups.',
    ecologicalFunction: 'Acoustic percussive shockwave audible over 1 km combined with sub-harmonic vocal fry.',
    canopyAcoustics: 'Ultra-low mechanical resonance driven by cupped palm impacts on air-sac inflated thorax at 18–25 beats per second.',
    phases: [
      {
        phaseNumber: 1,
        name: 'Thoracic Air-Sac Beat',
        sipaNotation: '[ ɓ͉-ɓ͉-ɓ͉ ]',
        acousticDescription: 'Rapid non-vocal percussive impacts on inflated chest laryngeal sacs generating sub-100 Hz pulses.',
        respiratoryDynamic: 'rapid_cycle',
        frequencyHz: 85,
        durationMs: 1900,
        airSacEngagement: true,
      },
      {
        phaseNumber: 2,
        name: 'Sub-Harmonic Grunt Roar',
        sipaNotation: '[ ɓ͉ɑ↓ ]',
        acousticDescription: 'Deep guttural roar with sub-harmonic tremor vibration and explosive diaphragm release.',
        respiratoryDynamic: 'egress',
        frequencyHz: 130,
        durationMs: 2200,
        airSacEngagement: true,
      },
    ],
    usdAudioSchemaAscii: `#usda 1.0
def AudioSource "Gorilla_ChestBeat_SIPA"
{
    string sipa:percussiveNotation = "[ ɓ͉-ɓ͉-ɓ͉ ]"
    float sipa:subHarmonicTremorHz = 85.0
    float sipa:chestCavityQ = 14.2
}`,
  },
];
